### PR TITLE
Include license in sdist

### PR DESCRIPTION
**Pull request by thewchan**
Include license in sdist by adding a MANIFEST.in file.

### CODE REVIEW

**Comment by CrossNox** [comment]
Hi @thewchan, thanks for the PR!
Would you mind elaborating into the `why` of this PR?
On another note, development is going on in [gitlab](https://gitlab.com/mutt_data/muttlib), this is just a mirror. I'm gonna make sure to state that on `CONTRIBUTING.md`.

**Comment by CrossNox** [comment]
Hi @thewchan, sure, I can see that, but why is this required? What purpose does it serve?

**Comment by thewchan** [comment]
Yes sorry, the context is that I have put this on conda forge, and they prefer the license file to be packaged into the source distribution. This can be done manually, but it's preferable is it is bundled in upstream in the sdist.

**Comment by MartinCura** [comment]
Replaced with #11. Now it's included in the releases. Thanks and sorry for the delay!

**Pull request closed without merging**
